//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NapolniRD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestDatas
    {
        public int Id { get; set; }
        public int IdPostaje { get; set; }
        public int Dan { get; set; }
        public int Mesec { get; set; }
        public int Leto { get; set; }
        public int Podatek1 { get; set; }
        public int Podatek2 { get; set; }
    }
}
